### ISSUE TITLE
If videos are uploaded in 720p or higher, you can use maxresdefault.jpg

### ISSUE THREAD

**Issue by themorgantown** [tylerpearson/lazyYT#12]
Line 32 can changed to: 

            'background': 'url(//img.youtube.com/vi/' + id + '/maxresdefault.jpg) center center no-repeat',

If all your youtube videos are uploaded at 720p or higher. This cleared up thumbnails up for me. 

Thanks Tyler!

**Comment by tylerpearson** [comment]
updated with https://github.com/tylerpearson/lazyYT/pull/13!

**Comment by tyrann0us** [comment]
I get a 404 on the maxresdefault.jpg with a video I try to embed (YR3_Qmn5El8).

What about adding a test to see if the requested thumbnail returnes a 404?
If that's is the case you would use a different thumbail size.
Thanks!

**Comment by jaskaran27** [comment]
I agree with @tyrann0us. I am getting 404s for a couple of video thumbnails as well. If the HD image is not available, it should fallback to the next available thumbnail image. That would be an ideal solution. 

Thanks for the plugin regardless. The speed improvement is remarkable!
