### ISSUE TITLE
What's the benefit of this over using the controls=2 parameter?

### ISSUE THREAD

**Issue by jordn** [tylerpearson/lazyYT#15]
https://developers.google.com/youtube/player_parameters#controls

    controls=2 – Player controls display in the player. For IFrame embeds, the controls
                 display and the Flash player loads after the user initiates the video playback.

**Comment by Daugilas** [comment]
@jordn it loads ~10 times faster when using lazyYT plugin.

lazyYT grid: http://works.daugilas.com/lazyYT/demo/grid.html
controls=2 grid: http://works.daugilas.com/lazyYT/demo/grid_controls2.html

In addition videos looks better with lazyYT.
