### ISSUE TITLE
Video title only shows "https://youtube.com/devicesupport"

### ISSUE THREAD

**Issue by donauweb** [tylerpearson/lazyYT#35]
Since 1 or 2 weeks the title of the video always shows "https://youtube.com/devicesupport" in stead of the real title. There must have been a change in YouTube.

**Comment by manyk** [comment]
@langenzersdorfer, what you say is a dupplicate of this issue here:  [Unable to get video title #34](https://github.com/tylerpearson/lazyYT/issues/34)

**Comment by donauweb** [comment]
Yes, true, this is a duplicate.
