### ISSUE TITLE
Safari: After exiting fullscreen video, player redraws incorrectly

### ISSUE THREAD

**Issue by kyleridolfo** [tylerpearson/lazyYT#36]
In Safari, when exiting fullscreen video, the player doesn’t redraw correctly. I've uploaded some screenshots of the lazyYT example before and after fullscreen. You can see it adds in an extra margin.

I've seen other weird issues in my own site where the player compresses to a small container that basically only shows the video controls.

I'm not able to reproduce this with videos on YouTube.com.

Let me know what other information might be helpful. Thanks!

![before](https://cloud.githubusercontent.com/assets/4280/7752026/43c45e12-ffab-11e4-8491-180439d29187.jpg)
![after](https://cloud.githubusercontent.com/assets/4280/7752025/43c438a6-ffab-11e4-8d39-523e98464bcb.jpg)

**Comment by Daugilas** [comment]
@yaykyle if you still would like this problem solved, could you check if the same happens when you add videos as a standard YouTube iframe embed?

**Comment by kyleridolfo** [comment]
So you mean just add them as an iframe embed without using lazyYT?

**Comment by Daugilas** [comment]
@yaykyle I have tried it on Safari back then and just now and I cannot recreate this problem...
The reason I asked you to try it with standard YouTube iframe was just to see if it makes any difference on your machine.

**Comment by kyleridolfo** [comment]
@Daugilas Hi! Sorry I just saw this now. I am no longer able to reproduce this. Very strange. Thank you for your help!
