### ISSUE TITLE
Updated YouTube UI CSS

### ISSUE THREAD

**Issue by jaskaran27** [tylerpearson/lazyYT#46]
I'd greatly appreciate if someone could manage to update the CSS to reflect YouTube's new UI.

**Comment by Daugilas** [comment]
@jaskaran27 updated! With this commit: https://github.com/Daugilas/lazyYT/commit/980011b64b0b6be6cab32699137088a4e37c9562

**Comment by jaskaran27** [comment]
@Daugilas This works perfectly. Thanks a lot!
