### ISSUE TITLE
Play button moves slightly to right and down without playing the video.

### ISSUE THREAD

**Issue by rotemberger** [tylerpearson/lazyYT#47]
In the demo pages  the play button moves about 50px right and down when clicking on it.

The play button returns to center position when the player looses focus.

![before](https://cloud.githubusercontent.com/assets/1023811/9679894/53b0c290-52fb-11e5-8f2b-3b417fbbb314.png)

![after](https://cloud.githubusercontent.com/assets/1023811/9679905/62f0f9fa-52fb-11e5-82e0-5ef9247e99bd.png)

Tested under Chrome and Mozilla browsers.

**Comment by Daugilas** [comment]
@rotemberger fixed with latest commit: https://github.com/Daugilas/lazyYT/commit/a7712d7af2804508012caf657345ee5a80bf3549
