### ISSUE TITLE
MIT or CC  license 

### ISSUE THREAD

**Issue by maruilian11** [tylerpearson/lazyYT#52]
hi, recently we want to add your lib on https://cdnjs.com, i saw CC BY-SA 4.0 license on master branch but MIT on tag 0.3.4, just want to confirm this with you.
thank you very much!

https://github.com/cdnjs/cdnjs/pull/6735

**Comment by PeterDaveHello** [comment]
Looks like this lib just changed its license to CC BY-SA 4.0 from MIT, that's all.

**Comment by maruilian11** [comment]
ok.
